name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push of Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/course
          docker build -t $IMAGE:latest -t $IMAGE:${GITHUB_SHA::7} .
          docker push $IMAGE:latest
          docker push $IMAGE:${GITHUB_SHA::7}
