name: CD

on:
  push:
    branches:
      - main

jobs:
  push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da imagem
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/fast-pizza
          docker build -t $IMAGE:latest -t $IMAGE:${GITHUB_SHA::7} .
          docker push $IMAGE:latest
          docker push $IMAGE:${GITHUB_SHA::7}
